"""Built-in workflow presets, roles and gate vocabulary (SPEC §5.4).

Presets are read-only starting points: copy one into your own templates to
edit it, or assign it to a project as-is. Every preset's stages must parse
with workflow.parse_stages() — a test enforces that.
"""

from __future__ import annotations

# Roles a stage can call for. Stage → agent matching uses these ids
# (project_agent_roles); the labels are for humans in the UI.
ROLES = [
    {"id": "product-planner", "label": "產品策劃", "hint": "產品目標、受眾、玩法與成功指標"},
    {"id": "pm", "label": "專案/產品經理", "hint": "規劃、驗收、對外溝通"},
    {"id": "system-analyst", "label": "系統分析師", "hint": "邊界、資料流、依賴、風險與驗收模型"},
    {"id": "software-architect", "label": "軟體架構師", "hint": "架構契約、模組責任與整合策略"},
    {"id": "engineer", "label": "工程師", "hint": "通用開發"},
    {"id": "backend-engineer", "label": "後端工程師", "hint": "API、資料層"},
    {"id": "frontend-engineer", "label": "前端工程師", "hint": "介面實作"},
    {"id": "mobile-engineer", "label": "行動端工程師", "hint": "iOS/Android"},
    {"id": "tester", "label": "測試工程師", "hint": "測試撰寫與執行"},
    {"id": "reviewer", "label": "審查者", "hint": "程式/內容審查"},
    {"id": "security-reviewer", "label": "安全審查者", "hint": "資安風險把關"},
    {"id": "ux-researcher", "label": "UX 研究／設計", "hint": "使用者流程、可用性與無障礙"},
    {"id": "ui-designer", "label": "UI 設計師", "hint": "資訊層級、元件、狀態與響應式規格"},
    {"id": "visual-artist", "label": "視覺美術", "hint": "視覺語言、素材、動態與資產規格"},
    {"id": "designer", "label": "通用設計師（相容）", "hint": "版型、使用者流程"},
    {"id": "integrator", "label": "整合工程師", "hint": "跨分支整合、契約核對與衝突處理"},
    {"id": "release-manager", "label": "Git／發布管理", "hint": "合併候選、主線、標籤與交付證據"},
    {"id": "researcher", "label": "研究員", "hint": "調查設計與資料蒐集"},
    {"id": "analyst", "label": "分析師", "hint": "數據與市場分析"},
    {"id": "writer", "label": "撰稿", "hint": "文件、腳本、報告"},
    {"id": "editor", "label": "編輯/剪輯", "hint": "潤稿、影音剪輯"},
    {"id": "producer", "label": "製作", "hint": "素材與流程協調"},
    {"id": "ops-engineer", "label": "運維工程師", "hint": "部署、監控、故障處理"},
    {"id": "maintainer", "label": "維護工程師", "hint": "相依更新、技術債、長期健康"},
]

# Gate vocabulary with human labels (engine semantics live in workflow.py)
GATES = [
    {"id": "auto", "label": "自動通過", "icon": "▶",
     "hint": "階段跑完就進下一關，適合不需把關的工作"},
    {"id": "tests-pass", "label": "測試通過", "icon": "✓",
     "hint": "由引擎執行你指定的指令，exit code 0 才過關"},
    {"id": "agent-review", "label": "AI 審核", "icon": "🔍",
     "hint": "審查 agent 必須回傳結構化裁決；沒有裁決一律不通過"},
    {"id": "human-approve", "label": "人工核准", "icon": "⏸",
     "hint": "停下來等人在看板或 Telegram 上按核准"},
]

EVIDENCE_TYPES = [
    {"id": "requirements", "label": "需求與範圍"},
    {"id": "architecture", "label": "架構與契約"},
    {"id": "functional", "label": "功能正確性"},
    {"id": "integration", "label": "跨模組整合"},
    {"id": "ux", "label": "使用者流程與可用性"},
    {"id": "visual", "label": "視覺與品牌一致性"},
    {"id": "accessibility", "label": "無障礙"},
    {"id": "security", "label": "安全與隱私"},
    {"id": "performance", "label": "效能"},
    {"id": "operations", "label": "部署與運維"},
    {"id": "git", "label": "Git 整合"},
    {"id": "delivery", "label": "交付與遠端收據"},
    {"id": "research-integrity", "label": "研究可追溯性"},
    {"id": "content-quality", "label": "內容品質與權利"},
]

DEVELOPMENT_EVIDENCE = {
    "requirements", "architecture", "functional", "integration", "security",
    "git", "delivery",
}

PRESETS = [
    {
        "id": "fullstack-dev",
        "name": "前後端程式開發",
        "family": "development",
        "required_evidence": sorted(DEVELOPMENT_EVIDENCE | {"ux", "visual"}),
        "description": "架構契約完成後，UX、視覺與後端並行；前端接合設計與 API，"
                       "再由整合、品質與安全角色獨立驗證。",
        "stages": [
            {"name": "需求與系統契約", "role": "system-analyst",
             "gate": "human-approve", "needs": [],
             "produces": ["system-contract"],
             "evidence": ["requirements", "architecture"],
             "desc": "凍結需求邊界、資料/API 契約、失敗模式與驗收模型"},
            {"name": "UX 流程規格", "role": "ux-researcher",
             "gate": "agent-review", "read_only": True,
             "needs": ["需求與系統契約"], "workspace": "isolated",
             "consumes": ["system-contract"], "produces": ["ux-spec"],
             "evidence": ["ux"],
             "desc": "使用者任務、流程、心智模型與錯誤恢復"},
            {"name": "UI 元件規格", "role": "ui-designer",
             "gate": "agent-review", "read_only": True,
             "needs": ["需求與系統契約"], "workspace": "isolated",
             "consumes": ["system-contract"], "produces": ["ui-spec"],
             "evidence": ["ux", "accessibility"],
             "desc": "資訊層級、元件狀態、響應式與無障礙規格"},
            {"name": "視覺美術規格", "role": "visual-artist", "gate": "agent-review",
             "needs": ["需求與系統契約"], "workspace": "isolated",
             "consumes": ["system-contract"], "produces": ["visual-spec"],
             "evidence": ["visual"], "desc": "視覺語言、素材、動態與資產規格"},
            {"name": "後端實作", "role": "backend-engineer", "gate": "tests-pass",
             "needs": ["需求與系統契約"], "workspace": "isolated",
             "consumes": ["system-contract"], "produces": ["backend-api"],
             "gate_config": {"command": "pytest -q"},
             "max_retries": 1, "evidence": ["functional"],
             "desc": "依凍結契約實作 API 與資料層"},
            {"name": "前端實作", "role": "frontend-engineer", "gate": "tests-pass",
             "needs": ["UX 流程規格", "UI 元件規格", "視覺美術規格", "後端實作"],
             "consumes": ["ux-spec", "ui-spec", "visual-spec", "backend-api"],
             "produces": ["frontend-app"],
             "gate_config": {"command": "npm test --silent"},
             "max_retries": 1, "evidence": ["functional", "ux", "visual"],
             "desc": "依 UX/視覺規格接合 API"},
            {"name": "整合測試", "role": "integrator", "gate": "tests-pass",
             "needs": ["前端實作", "後端實作"],
             "consumes": ["frontend-app", "backend-api"],
             "produces": ["integration-candidate"],
             "gate_config": {"command": "pytest -q && npm test --silent"},
             "evidence": ["functional", "integration", "git"],
             "desc": "合流分支並驗證完整系統"},
            {"name": "程式審查", "role": "reviewer", "gate": "agent-review",
             "needs": ["整合測試"], "read_only": True,
             "consumes": ["integration-candidate"], "produces": ["code-review"],
             "evidence": ["architecture", "git"],
             "desc": "唯讀挑戰架構、可維護性與 Git diff"},
            {"name": "安全審查", "role": "security-reviewer", "gate": "agent-review",
             "needs": ["整合測試"], "read_only": True,
             "consumes": ["integration-candidate"], "produces": ["security-review"],
             "evidence": ["security"], "desc": "威脅、權限、秘密與供應鏈風險"},
            {"name": "合併發布", "role": "release-manager", "gate": "human-approve",
             "needs": ["程式審查", "安全審查"],
             "consumes": ["code-review", "security-review"],
             "delivery_modes": ["integration", "production"],
             "evidence": ["git", "delivery"],
             "desc": "核對目標分支、遠端 commit 與交付 receipt 後放行"},
        ],
    },
    {
        "id": "web-dev",
        "name": "網頁開發",
        "family": "development",
        "required_evidence": sorted(DEVELOPMENT_EVIDENCE |
                                    {"ux", "visual", "accessibility", "performance"}),
        "description": "系統契約後並行完成 UX/UI 與視覺規格，再實作頁面；E2E、"
                       "無障礙與安全審查並行取證後才可上線。",
        "stages": [
            {"name": "需求與版型", "role": "system-analyst", "gate": "human-approve",
             "needs": [], "produces": ["web-contract"],
             "evidence": ["requirements", "architecture"],
             "desc": "確認使用者目標、頁面狀態、資料契約與驗收條件"},
            {"name": "UX 與 UI 設計", "role": "ui-designer", "gate": "agent-review",
             "read_only": True, "needs": ["需求與版型"], "workspace": "isolated",
             "consumes": ["web-contract"], "produces": ["ui-spec"],
             "evidence": ["ux", "accessibility"],
             "desc": "流程、資訊架構、元件狀態與響應式規格"},
            {"name": "視覺美術", "role": "visual-artist", "gate": "agent-review",
             "needs": ["需求與版型"], "workspace": "isolated",
             "consumes": ["web-contract"], "produces": ["visual-assets"],
             "evidence": ["visual"], "desc": "色彩、字體、圖像、動態與資產"},
            {"name": "頁面實作", "role": "frontend-engineer", "gate": "auto",
             "needs": ["UX 與 UI 設計", "視覺美術"],
             "consumes": ["ui-spec", "visual-assets"], "produces": ["web-build"],
             "max_retries": 1, "timeout_s": 7200,
             "desc": "依設計契約完成切版、狀態與互動"},
            {"name": "響應式與無障礙檢查", "role": "reviewer", "gate": "agent-review",
             "needs": ["頁面實作"], "consumes": ["web-build"],
             "produces": ["a11y-review"],
             "gate_config": {"precheck_command": "npm run test:e2e"},
             "requires": ["browser.playwright"],
             "read_only": True, "rework_target": "頁面實作",
             "evidence": ["ux", "accessibility", "performance"],
             "desc": "Bastet 先在 sandbox 外跑 E2E，再交證據審查 RWD、無障礙與語意"},
            {"name": "E2E 測試", "role": "tester", "gate": "tests-pass",
             "needs": ["頁面實作"], "read_only": True,
             "consumes": ["web-build"], "produces": ["e2e-evidence"],
             "gate_config": {"command": "npm run test:e2e"},
             "requires": ["browser.playwright"],
             "rework_target": "頁面實作",
             "evidence": ["functional", "integration"],
             "desc": "瀏覽器流程自動化測試"},
            {"name": "安全審查", "role": "security-reviewer", "gate": "agent-review",
             "needs": ["頁面實作"], "read_only": True,
             "consumes": ["web-build"], "produces": ["web-security-review"],
             "evidence": ["security"], "desc": "前端供應鏈、輸入、權限與秘密檢查"},
            {"name": "上線核准", "role": "release-manager", "gate": "human-approve",
             "needs": ["響應式與無障礙檢查", "E2E 測試", "安全審查"],
             "consumes": ["a11y-review", "e2e-evidence", "web-security-review"],
             "delivery_modes": ["integration", "production"],
             "evidence": ["git", "delivery"],
             "desc": "核對目標分支、遠端 commit 與部署證據後放行"},
        ],
    },
    {
        "id": "mobile-app",
        "name": "手機 APP 開發",
        "family": "development",
        "required_evidence": sorted(DEVELOPMENT_EVIDENCE |
                                    {"ux", "visual", "accessibility"}),
        "description": "系統契約後並行完成行動 UX 與視覺資產，整合實作後由建置、"
                       "程式與安全審查並行驗證。",
        "stages": [
            {"name": "規格與畫面流程", "role": "system-analyst", "gate": "human-approve",
             "needs": [], "produces": ["mobile-contract"],
             "evidence": ["requirements", "architecture"],
             "desc": "定義平台邊界、狀態、資料契約與驗收標準"},
            {"name": "行動 UX/UI", "role": "ux-researcher", "gate": "agent-review",
             "read_only": True, "needs": ["規格與畫面流程"], "workspace": "isolated",
             "consumes": ["mobile-contract"], "produces": ["mobile-ux"],
             "evidence": ["ux", "accessibility"], "desc": "導覽、手勢、狀態與可及性"},
            {"name": "視覺與商店資產", "role": "visual-artist", "gate": "agent-review",
             "needs": ["規格與畫面流程"], "workspace": "isolated",
             "consumes": ["mobile-contract"], "produces": ["mobile-visual"],
             "evidence": ["visual"], "desc": "視覺元件、圖示、截圖與商店素材"},
            {"name": "功能實作", "role": "mobile-engineer", "gate": "auto",
             "needs": ["行動 UX/UI", "視覺與商店資產"],
             "consumes": ["mobile-ux", "mobile-visual"], "produces": ["mobile-build"],
             "max_retries": 1,
             "desc": "依契約整合畫面、平台能力與商業邏輯"},
            {"name": "建置與單元測試", "role": "tester", "gate": "tests-pass",
             "needs": ["功能實作"], "read_only": True,
             "consumes": ["mobile-build"], "produces": ["mobile-test-evidence"],
             "gate_config": {"command": "make test"},
             "evidence": ["functional", "integration"],
             "desc": "確認可建置且測試通過"},
            {"name": "程式審查", "role": "reviewer", "gate": "agent-review",
             "needs": ["功能實作"], "read_only": True,
             "consumes": ["mobile-build"], "produces": ["mobile-code-review"],
             "evidence": ["architecture", "git"], "desc": "唯讀審查變更"},
            {"name": "安全與隱私審查", "role": "security-reviewer",
             "gate": "agent-review", "needs": ["功能實作"], "read_only": True,
             "consumes": ["mobile-build"], "produces": ["mobile-security-review"],
             "evidence": ["security"], "desc": "權限、資料保護、秘密與隱私揭露"},
            {"name": "送審準備", "role": "release-manager", "gate": "human-approve",
             "needs": ["建置與單元測試", "程式審查", "安全與隱私審查"],
             "consumes": ["mobile-test-evidence", "mobile-code-review",
                          "mobile-security-review"],
             "delivery_modes": ["integration", "production"],
             "evidence": ["git", "delivery"],
             "desc": "核對版本、目標分支、商店資料與送審 receipt"},
        ],
    },
    {
        "id": "market-research",
        "name": "市場調查",
        "family": "research",
        "required_evidence": ["requirements", "research-integrity", "content-quality",
                              "delivery"],
        "description": "調查設計後讓公開資料與使用者/市場訊號並行蒐集，再整合分析、"
                       "獨立挑戰洞察並交付報告。",
        "stages": [
            {"name": "調查設計", "role": "researcher", "gate": "human-approve",
             "needs": [], "produces": ["research-plan"],
             "evidence": ["requirements", "research-integrity"],
             "desc": "界定問題、對象、方法、來源品質與停止條件"},
            {"name": "公開資料與競品蒐集", "role": "researcher", "gate": "auto",
             "needs": ["調查設計"], "workspace": "isolated",
             "consumes": ["research-plan"], "produces": ["desk-research"],
             "desc": "保留來源、日期與可追溯摘錄"},
            {"name": "使用者與市場訊號蒐集", "role": "researcher", "gate": "auto",
             "needs": ["調查設計"], "workspace": "isolated",
             "consumes": ["research-plan"], "produces": ["field-research"],
             "desc": "訪談、問卷與市場訊號整理"},
            {"name": "市場與競品分析", "role": "analyst", "gate": "auto",
             "needs": ["公開資料與競品蒐集", "使用者與市場訊號蒐集"],
             "consumes": ["desk-research", "field-research"],
             "produces": ["market-analysis"],
             "desc": "合流資料後量化與趨勢判讀"},
            {"name": "洞察審核", "role": "reviewer", "gate": "agent-review",
             "needs": ["市場與競品分析"], "read_only": True,
             "consumes": ["market-analysis"], "produces": ["validated-insights"],
             "evidence": ["research-integrity"],
             "desc": "挑戰推論是否有資料支撐、是否過度延伸"},
            {"name": "報告產出", "role": "writer", "gate": "auto",
             "needs": ["洞察審核"], "consumes": ["validated-insights"],
             "produces": ["market-report"],
             "desc": "撰寫可追溯來源與限制的交付報告"},
            {"name": "交付核准", "role": "pm", "gate": "human-approve",
             "needs": ["報告產出"], "consumes": ["market-report"],
             "evidence": ["content-quality", "delivery"],
             "desc": "確認結論、限制與附件後交付"},
        ],
    },
    {
        "id": "academic-research",
        "name": "學術研究",
        "family": "research",
        "required_evidence": ["requirements", "research-integrity", "content-quality",
                              "delivery"],
        "description": "研究問題核准後並行進行文獻回顧與方法設計，合流後分析、"
                       "獨立驗證、撰稿與定稿。",
        "stages": [
            {"name": "研究問題", "role": "researcher", "gate": "human-approve",
             "needs": [], "produces": ["research-question"],
             "evidence": ["requirements", "research-integrity"],
             "desc": "確立問題、範圍、假設與倫理邊界"},
            {"name": "文獻回顧", "role": "researcher", "gate": "agent-review",
             "needs": ["研究問題"], "workspace": "isolated",
             "consumes": ["research-question"], "produces": ["literature-review"],
             "evidence": ["research-integrity"], "desc": "可追溯搜尋與研究缺口整理"},
            {"name": "方法設計", "role": "researcher", "gate": "human-approve",
             "needs": ["研究問題"], "workspace": "isolated",
             "consumes": ["research-question"], "produces": ["research-method"],
             "evidence": ["research-integrity"],
             "desc": "設計方法、資料來源、排除標準與可重現步驟"},
            {"name": "資料分析", "role": "analyst", "gate": "auto",
             "needs": ["文獻回顧", "方法設計"],
             "consumes": ["literature-review", "research-method"],
             "produces": ["analysis-result"],
             "desc": "合流理論與方法後執行可重現分析"},
            {"name": "結果驗證", "role": "reviewer", "gate": "agent-review",
             "needs": ["資料分析"], "read_only": True,
             "consumes": ["analysis-result"], "produces": ["validated-result"],
             "evidence": ["research-integrity"],
             "desc": "挑戰結論與資料一致性、方法誤用與替代解釋"},
            {"name": "論文撰寫", "role": "writer", "gate": "auto",
             "needs": ["結果驗證"], "consumes": ["validated-result"],
             "produces": ["manuscript"],
             "desc": "依格式撰寫、標註引用並揭露限制"},
            {"name": "定稿審閱", "role": "editor", "gate": "human-approve",
             "needs": ["論文撰寫"], "consumes": ["manuscript"],
             "evidence": ["content-quality", "delivery"], "desc": "潤稿與最終確認"},
        ],
    },
    {
        "id": "video-production",
        "name": "影片製作",
        "family": "media",
        "required_evidence": ["requirements", "visual", "content-quality", "delivery"],
        "description": "企劃核准後讓視覺素材與聲音/權利素材並行，合流剪輯後由內容"
                       "與視覺角色獨立審核。",
        "stages": [
            {"name": "企劃與腳本", "role": "writer", "gate": "human-approve",
             "needs": [], "produces": ["approved-script"],
             "evidence": ["requirements", "content-quality"],
             "desc": "主題、受眾、結構、逐字腳本與權利邊界"},
            {"name": "視覺素材準備", "role": "visual-artist", "gate": "auto",
             "needs": ["企劃與腳本"], "workspace": "isolated",
             "consumes": ["approved-script"], "produces": ["visual-media"],
             "desc": "畫面、圖像、動態與字卡素材"},
            {"name": "聲音與權利素材", "role": "producer", "gate": "auto",
             "needs": ["企劃與腳本"], "workspace": "isolated",
             "consumes": ["approved-script"], "produces": ["audio-rights-media"],
             "desc": "配樂、旁白、授權與來源清單"},
            {"name": "剪輯", "role": "editor", "gate": "auto",
             "needs": ["視覺素材準備", "聲音與權利素材"],
             "consumes": ["visual-media", "audio-rights-media"],
             "produces": ["video-candidate"],
             "desc": "合流影片、字幕與聲音"},
            {"name": "內容審核", "role": "reviewer", "gate": "agent-review",
             "needs": ["剪輯"], "read_only": True,
             "consumes": ["video-candidate"], "produces": ["content-review"],
             "evidence": ["content-quality"], "desc": "事實、版權與敘事一致性"},
            {"name": "視覺審核", "role": "visual-artist", "gate": "agent-review",
             "needs": ["剪輯"], "read_only": True,
             "consumes": ["video-candidate"], "produces": ["visual-review"],
             "evidence": ["visual"], "desc": "品牌、構圖、動態、字幕與可讀性"},
            {"name": "成品核准", "role": "pm", "gate": "human-approve",
             "needs": ["內容審核", "視覺審核"],
             "consumes": ["content-review", "visual-review"],
             "evidence": ["delivery"], "desc": "確認成品與權利清單後才發布"},
        ],
    },
    {
        "id": "ops-incident",
        "name": "運維處理",
        "family": "operations",
        "required_evidence": ["requirements", "functional", "integration", "security",
                              "operations", "git", "delivery"],
        "description": "線上狀況的處理循環：定位 → 止血 → 根因 → 修復驗證 → "
                       "部署 → 事後記錄。以最短時間恢復服務為第一優先。",
        "stages": [
            {"name": "問題定位", "role": "ops-engineer", "gate": "auto",
             "needs": [], "produces": ["incident-scope"],
             "desc": "重現與收斂影響範圍、時間軸及現況"},
            {"name": "緊急處置", "role": "ops-engineer", "gate": "human-approve",
             "needs": ["問題定位"], "read_only": True,
             "consumes": ["incident-scope"], "produces": ["approved-mitigation"],
             "evidence": ["operations"],
             "desc": "提出可回滾止血方案；核准只是授權方案，不由 Agent 偷做副作用"},
            {"name": "根因分析", "role": "system-analyst", "gate": "agent-review",
             "needs": ["問題定位"], "read_only": True,
             "consumes": ["incident-scope"], "produces": ["root-cause"],
             "evidence": ["requirements", "architecture", "operations"],
             "desc": "挑戰症狀解釋並建立可證偽根因"},
            {"name": "修復與回歸測試", "role": "backend-engineer",
             "gate": "tests-pass",
             "needs": ["緊急處置", "根因分析"],
             "consumes": ["approved-mitigation", "root-cause"],
             "produces": ["incident-fix"],
             "gate_config": {"command": "pytest -q"},
             "max_cycles": 3,
             "evidence": ["functional", "integration"],
             "desc": "修好並補上能重現這個故障的測試；沒過就自己修到過"},
            {"name": "變更審查", "role": "reviewer", "gate": "agent-review",
             "needs": ["修復與回歸測試"], "read_only": True,
             "consumes": ["incident-fix"], "produces": ["incident-review"],
             "rework_target": "修復與回歸測試", "evidence": ["git", "security"],
             "desc": "唯讀檢查修復是否對症、有無新風險"},
            {"name": "部署上線", "role": "release-manager", "gate": "human-approve",
             "needs": ["變更審查"], "consumes": ["incident-review"],
             "produces": ["incident-delivery"], "on_fail": "block",
             "evidence": ["operations", "git", "delivery"],
             "desc": "核對目標分支、回滾點與部署 receipt，由人放行"},
            {"name": "事後記錄", "role": "writer", "gate": "human-approve",
             "needs": ["部署上線"], "consumes": ["incident-delivery"],
             "evidence": ["operations", "delivery"],
             "desc": "時間軸、根因、後續行動；確認後才結案並進團隊記憶"},
        ],
    },
    {
        "id": "continuous-maintenance",
        "name": "持續維護",
        "family": "maintenance",
        "required_evidence": ["architecture", "functional", "integration", "security",
                              "operations", "git", "delivery"],
        "description": "已上線專案的定期維護：健康檢查 → 相依與安全更新 → "
                       "回歸測試 → 技術債整理 → 驗收。適合排程反覆執行。",
        "stages": [
            {"name": "健康檢查", "role": "maintainer", "gate": "agent-review",
             "read_only": True,
             "needs": [], "produces": ["health-baseline"],
             "evidence": ["architecture", "operations", "performance"],
             "desc": "盤點錯誤、效能、待辦、過期相依與基準 commit"},
            {"name": "相依與安全更新", "role": "maintainer", "gate": "tests-pass",
             "needs": ["健康檢查"], "workspace": "isolated",
             "consumes": ["health-baseline"], "produces": ["dependency-update"],
             "gate_config": {"command": "pytest -q"},
             "max_cycles": 3,
             "evidence": ["functional", "security"],
             "desc": "升級套件並修掉升級帶來的破壞；測試必須綠燈"},
            {"name": "技術債整理", "role": "maintainer", "gate": "auto",
             "needs": ["健康檢查"], "workspace": "isolated",
             "consumes": ["health-baseline"], "produces": ["debt-cleanup"],
             "desc": "與相依更新隔離並行的小步重構與文件補強"},
            {"name": "回歸測試", "role": "tester", "gate": "tests-pass",
             "needs": ["相依與安全更新"], "read_only": True,
             "workspace": "isolated",
             "consumes": ["dependency-update"], "produces": ["regression-evidence"],
             "gate_config": {"command": "pytest -q"},
             "rework_target": "相依與安全更新",
             "evidence": ["functional", "integration"],
             "desc": "完整跑一次；失敗就退回上一階段修"},
            {"name": "維護審查", "role": "reviewer", "gate": "agent-review",
             "needs": ["技術債整理"], "read_only": True,
             "workspace": "isolated",
             "consumes": ["debt-cleanup"], "produces": ["maintenance-review"],
             "rework_target": "技術債整理", "evidence": ["architecture", "git"],
             "desc": "確認這一輪沒有偷偷改變行為"},
            {"name": "安全審查", "role": "security-reviewer", "gate": "agent-review",
             "needs": ["相依與安全更新"], "read_only": True,
             "workspace": "isolated",
             "consumes": ["dependency-update"], "produces": ["maintenance-security"],
             "rework_target": "相依與安全更新", "evidence": ["security"],
             "desc": "檢查漏洞、鎖檔與供應鏈差異"},
            {"name": "維護驗收", "role": "release-manager", "gate": "human-approve",
             "needs": ["回歸測試", "維護審查", "安全審查"],
             "consumes": ["regression-evidence", "maintenance-review",
                          "maintenance-security"],
             "evidence": ["operations", "git", "delivery"],
             "desc": "核對合流 commit、遠端 receipt 與維護摘要"},
        ],
    },
]


def preset(preset_id: str) -> dict | None:
    return next((p for p in PRESETS if p["id"] == preset_id), None)
